### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by zepinglee** [zepinglee/gbt-7714-2015#1]
测试：

- [ ] 标点符号全角／半角

- [ ] 空白距离

- [ ] url 的断行

**Comment by zepinglee** [comment]
@seisman 现在差不多了，你可以测试一下

**Comment by zepinglee** [comment]
@Liam0205 我对空白的距离还拿不太准，希望你能提一些意见

**Comment by Liam0205** [comment]
我看一下。

**Comment by nanmu42** [comment]
建议你把这个项目提交到CTAN，这样开发者们在做国内大学论文模板时都可以直接引用你的项目。:)

Zeping Lee <notifications@github.com> 於 2016年7月5日週二 06:34 寫道：

**Comment by zepinglee** [comment]
嗯，我正在欧洲玩呢，回去处理

**Comment by zepinglee** [comment]
@nanmu42 ctan 上面太缺乏 quality control 了, publisher 一大堆中国野鸡大学的模板, 我不想提交到这个上面

**Comment by nanmu42** [comment]
还是推荐您提交一下。

CTAN的初衷是一个分发者（正如其名），他们的相关工作是由七个志愿者来完成的。这是一个人力物力都比较吃紧的组织。
另外一方面，整个TeX体系都是这样建立起来的吧，世界各地的贡献者们一同贡献，能够热心参与其实已经很不容易。
出于上面两个原因，个人感觉没有设置同行评议之类的QC手段还是有苦衷的。

您说的国内野鸡大学模板泛滥这个问题，我并没有感受，我想，质量控制和受众大小其实应该交由市场自己决定。CTAN上6000+个宏包，我们常用的也就那么几十个，这个情况也说明了这个问题。

作为CQUThesis的作者，我是很希望能够在模板中直接load您的作品，这是一个既便利又简洁的方法，我相信很多模板作者也会这么想。
优质项目对社群的推动作用会很明显。

祝好！

Zeping Lee <notifications@github.com> 於 2016年7月14日週四 17:38 寫道：

**Comment by Stone-Zeng** [comment]
@zepinglee 我也希望您可以把这个包发布到 CTAN。现在我在写 `fduthesis`，如果可以直接调用宏包的话大家用起来也会比较方便。

**Comment by zepinglee** [comment]
你们复旦是用的gbt 7714-2015，没有一点修改？

**Comment by Stone-Zeng** [comment]
2017 年 3 月修订的复旦大学博士、硕士学位论文规范要求为：

> 全文参考文献一览，各类参考文献编排格式须符合国家标准 GB/T 7714—2015《信息与文献：参考文献著录规则。

**Comment by zepinglee** [comment]
那好吧，我以为各个大学都会修改一点，没有完全按照那个规范的；而 bst 自定义很麻烦，就不适合作为一个宏包发布。

既然如此，我就完善一下文档后提交上去吧

**Comment by nanmu42** [comment]
Cool!
