### ISSUE TITLE
中文期刊无卷号，显示错误

### ISSUE THREAD

**Issue by saccohuo** [zepinglee/gbt-7714-2015#10]
中文期刊中很多格式为20xx年第xx期，没有卷号。
看到标准里面第12页没有卷号的都是省略卷号，但是使用这个文件生成的跟标准中不太一致（多个逗号），且使用bibtex编译的时候会提示warning。
下面是标准中的要求：
![image](https://cloud.githubusercontent.com/assets/13887263/17238120/74fcd04a-558b-11e6-9823-c562813a11f7.png)

下面是编译出来的结果：
![image](https://cloud.githubusercontent.com/assets/13887263/17238126/8b8ad276-558b-11e6-8d8f-384e19a6ef29.png)

下面是bibtex编译的warning：
![image](https://cloud.githubusercontent.com/assets/13887263/17238135/acab8c66-558b-11e6-95ea-7ab405d87665.png)

**Comment by zepinglee** [comment]
把你原来的 bib 贴出来我来测试一下

**Comment by zepinglee** [comment]
fixed in 0c2c6be

**Comment by saccohuo** [comment]
fix 这么迅速。。但是我测试了一下，sort方式好像挂掉了。参考文献排序方式不是按照引用顺序了。
下面是我的bib文件：
https://gist.github.com/saccohuo/de253da44df740655b1040735a9b813c

**Comment by zepinglee** [comment]
numerical 是按照引用顺序排序的，author-year 不是
