### ISSUE TITLE
conference和inproceedings析出文献格式

### ISSUE THREAD

**Issue by saccohuo** [zepinglee/gbt-7714-2015#11]
1. conference和inproceedings这两种析出文献不是应该在会议名称前面加上双斜杠吗？
2. 这两种析出文献为什么会在卷号前面加上了标识符 volume，我找了一下标准，似乎没提到卷号该怎么表示，但是直接使用volume x来标识，显得有点长。
3. 会议录经常是没有issue编号的，按理说对这部分留空即可，但是编译得到的结果是把这部分替换为了[S.l.] 。
下面是我编译得到的格式：
![image](https://cloud.githubusercontent.com/assets/13887263/17238611/bb27b2de-558f-11e6-8f85-c3444864f1c9.png)

下面是我的bibtex文件中的这个部分：
![image](https://cloud.githubusercontent.com/assets/13887263/17238620/dc1957ae-558f-11e6-987b-7c4080c310d5.png)

**Comment by zepinglee** [comment]
别截图啊，拷贝过来我好测试

1. inproceedings 应该是会加双斜杠的
2. 加 volume 是自动处理 booktitle 域时加的，我沿用了 plain.bst 的传统
3. s.l. 是出版地不详，我按照规定加的

**Comment by saccohuo** [comment]
Sorry，忘记直接贴文本了。
[S.l.]的地方原来是出版地啊，我以为是issue编号呢，那我问个题外话：会议的出版地一般是写开会地点？还是写什么呢？（我对这个了解比较少）

下面是bibtex：
```
@inproceedings{sedghara_reconfigurable_2013,
  title = {Reconfigurable single-feed antenna with switchable polarization},
  timestamp = {2015-10-09T09:13:22Z},
  booktitle = {2013 21st {{Iranian Conference}} on {{Electrical Engineering}} ({{ICEE}})},
  author = {Sedghara, A. and Atlasbaf, Z.},
  year = {2013},
  pages = {1--4},
}
```

**Comment by zepinglee** [comment]
写开会地点应该也没问题

**Comment by zepinglee** [comment]
双斜杠 确实有 bug

**Comment by zepinglee** [comment]
fixed in d2b0d80

**Comment by saccohuo** [comment]
试了一下，可以了，辛苦了
