### ISSUE TITLE
请教一下那个拼音域是怎么用的？

### ISSUE THREAD

**Issue by goldmonkey163com** [zepinglee/gbt-7714-2015#12]
我在test.bib里试了试添加pinyin= {a}之类的，发现顺序好像没怎么变？不太清楚到底怎么用

如果不需要英文名字大写的话，是不是按照https://github.com/zepinglee/gbt-7714-2015/commit/a7a2314de90dc3c56c39f081ec981616de313674 这里面的改回去就行了？

还有，如果需要把这个bst用在其他论文模板上，能不能提示一下需要什么其他改动？

**Comment by zepinglee** [comment]
在你调用 author-year 风格时，pinyin 域才会起作用

**Comment by zepinglee** [comment]
pinyin 主要是为了解决中文的排序问题；

改动主要是要把 gbt 要求的域设置正确

**Comment by goldmonkey163com** [comment]
谢谢

如果把这个bst用在其他论文模板上，makefile文件应该怎么办呢？

**Comment by zepinglee** [comment]
不需要修改内容，因为 bibtex 会自动调用相应的 style 文件。
不过我一般使用 latexmk，比直接用 makefile 要方便

**Comment by goldmonkey163com** [comment]
谢谢，最近改成TeXstudio，好像还挺方便的

不过突然意识到，这个bst没有编号。。。

**Comment by zepinglee** [comment]
有两个 bst，对应两种不同的风格

**Comment by goldmonkey163com** [comment]
就是改成\bibliographystyle{gbt-7714-2015-numerical}吗？
我试了试\setcitestyle{super,square,comma,sort&compress}，参考文献列表是有编号的。
但是\setcitestyle{authoryear,round,comma,aysep={,},yysep={;}}就不行。
偏偏我们的要求是文中是authoryear，文末按姓氏拼音排序，参考文献列表还要有编号，都不知道怎么做了。。。

**Comment by zepinglee** [comment]
\setcitestyle 确实会影响到后面的效果，具体参考 natbib 的文档。

你们用的不是标准 gbt-7714-2015，可能需要自行修改 bst。

**Comment by goldmonkey163com** [comment]
谢谢
