### ISSUE TITLE
英文作者姓如何全部大写

### ISSUE THREAD

**Issue by cughanchao** [zepinglee/gbt-7714-2015#13]
首先非常感谢你的这个bst文件。然后我有个小问题。
参考文献列表中，英文条目的作者姓氏只有首字母大写，请问如何能变成整个姓氏都大写？

**Comment by nanmu42** [comment]
Issue #7 可能对你有帮助。 @cughanchao

**Comment by cughanchao** [comment]
谢谢，明白了。之前没看到那个Issue。
