### ISSUE TITLE
作者和et al之间应该没有逗号

### ISSUE THREAD

**Issue by RuiShe** [zepinglee/gbt-7714-2015#14]
使用您的编译出来作者和et al之间有逗号，2015标准里应该没有逗号。或者是我的设置有问题？谢谢解答

<img width="155" alt="screen shot 2016-11-10 at 17 46 45" src="https://cloud.githubusercontent.com/assets/8948465/20171884/af3efe2a-a76d-11e6-8415-1b631b3588f8.png">

**Comment by zepinglee** [comment]
2015 标准的 citation 没有例子，我按照reference list 的样子写的；

你在标准里找到没有逗号的例子嘛？

**Comment by RuiShe** [comment]
标准里没有给出样例，但说的还是比较清楚，只在作者和“et al.” 之间留适当空隙，没有说逗号：
<img width="735" alt="screen shot 2016-11-14 at 13 25 12" src="https://cloud.githubusercontent.com/assets/8948465/20254292/daac57da-aa6d-11e6-90b8-b145d154b223.png">

然后我参考的清华大学的学位论文给出的标准，他们是完全按照2015标准的：
<img width="656" alt="screen shot 2016-11-14 at 13 28 23" src="https://cloud.githubusercontent.com/assets/8948465/20254330/43f038a6-aa6e-11e6-8306-7dbf39a95e50.png">
可见作者和“等”或“et al.”之间没有逗号

另外按上面标准，单作者时作者（多作者时的“et al."，”等“）与年份之间要留逗号。

**Comment by zepinglee** [comment]
fixed in b1383e8

**Comment by zepinglee** [comment]
中文的“等”前的空袭 963aec9

**Comment by RuiShe** [comment]
thanks for your work

**Comment by RuiShe** [comment]
另外请教一下，我想把reference list 作者名字全部大写改为只有首字母大写，要怎么修改呢？在标准里说这两种都可以，我是偏爱首字母大写的。谢谢！

**Comment by zepinglee** [comment]
参考 a7a2314

**Comment by Wzt1714** [comment]
问题同上，在[gbt7714-2005-numerical](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-2005-numerical.bst)中会有多个作者后逗号加'等'的问题。
![image](https://user-images.githubusercontent.com/64623205/236843896-3e1e90e3-092b-462c-b0c5-acb5c7177206.png)
