### ISSUE TITLE
英文作者的姓名格式是错误的

### ISSUE THREAD

**Issue by GitatHub** [zepinglee/gbt-7714-2015#15]
https://github.com/mohuangrui/ucasthesis/issues/17

1. 英文姓名缩写后面的 点 '.' 必须保留，但是 BST 里却都删除了，这是错误的，比如 **Webb J.** 变成了错误的  **Webb J**
2. 英文姓在前面的时候，必须加逗号， 比如 **WEBB, James** 而非 **WEBB James**
3. 期刊名称应该用 emph，也即英文名称应该是斜体，中文一般会换成楷体

这种参考文献格式根本过不了评阅这一关。。。

暂时只能用 plainnat 凑合，但是显然也是不符合“国标”的

**Comment by zepinglee** [comment]
> 1. 英文姓名缩写后面的 点 '.' 必须保留，但是 BST 里却都删除了，这是错误的，比如 Webb J. 变成了错误的 Webb J
> 2. 英文姓在前面的时候，必须加逗号， 比如 WEBB, James 而非 WEBB James
> 3. 期刊名称应该用 emph，也即英文名称应该是斜体，中文一般会换成楷体

你自己去看GBT7714-2015标准，哪不对你给我找个例子。

> 这种参考文献格式根本过不了评阅这一关。。。
暂时只能用 plainnat 凑合，但是显然也是不符合“国标”的

过不了评阅那你自己写一个啊，别在这BB

**Comment by nanmu42** [comment]
哈哈哈哈哈哈！别吵架，善待小白，和气生才。

Zeping Lee <notifications@github.com> 於 2017年2月26日 週日 上午9:10 寫道：

**Comment by GitatHub** [comment]
谢谢指点。你的 BST 没问题，有问题的是 GB。在这一点上，GB 绝对淋漓尽致地体现了四个自信。
