### ISSUE TITLE
引用网页格式问题

### ISSUE THREAD

**Issue by wayne508** [zepinglee/gbt-7714-2015#16]
引用网页应该“文献类型标识”应该为EB
但这里显示的都是M
谢谢

**Comment by zepinglee** [comment]
我好像忘记写“电子公告”的文献类型了，你可以提供你的 bib item 嘛？

**Comment by wayne508** [comment]
@online{xen,
	author = {XenProject},
	title = {The Xen Project, the powerful open source industry standard for virtualization},
	year = {2017},
	url = {https://www.xenproject.org/},
	urldate = {2017-03-16},
}

@misc{ wiki:kvm,
   author = "KVM",
   title = "Main Page --- KVM{,} ",
   year = "2016",
   url = "https://www.linux-kvm.org/index.php?title=Main_Page&oldid=173792",
   note = "[Online; accessed 17-March-2017]"
 }

第一个是自己写的，第二个是网站提供的。

**Comment by zepinglee** [comment]
我稍后把 online 补上；

至于misc 类型，我稍微加一点自动判断吧

**Comment by zepinglee** [comment]
fixed in 82a3c69
