### ISSUE TITLE
当一篇文献只有两个作者时，是不是应该列出两个作者的姓？

### ISSUE THREAD

**Issue by GitatHub** [zepinglee/gbt-7714-2015#17]
比如 A and B 2007 而非现在的 A et al. 2007？

**Comment by RuiShe** [comment]
![screen shot 2017-04-25 at 17 00 53](https://cloud.githubusercontent.com/assets/8948465/25377006/d1cbbc4c-29d8-11e7-8027-891504dcbd70.png)
国标是这样，你说的可能是某些期刊的习惯

**Comment by zepinglee** [comment]
感谢指出！
