### ISSUE TITLE
需要测试用的 bib 数据库

### ISSUE THREAD

**Issue by zepinglee** [zepinglee/gbt-7714-2015#2]
我想把 GBT 7714-2015 的附录作为测试用的 bib 文件，最好跟 Google Scholar 一样吧，（据我所了解大部分人会用google scholar 导出 bibtex）不知道有没有什么自动方法？

**Comment by LUXUV587** [comment]
什么意思？像Endnote、Mendeley都可以输出bib文件的。根据2015年的新标准做一个新的bst文件也是好厉害！

**Comment by zepinglee** [comment]
就是希望人来制作《标准》附录的bib数据库，无论用endnote 还是 mendeley 都要手工录入啊，而我对这些工具也不太熟。

**Comment by LUXUV587** [comment]
你可以找找用endnote的师兄师姐，一般硕士以上都会开始用到的，写篇journal article的文献一般是要在50篇以上。很多厉害的人博士毕业了，endnote里面的文献量都是好几千甚至上万。一次性导出个一两百条很轻松地。

**Comment by szsdk** [comment]
我这有[《标准2005》](https://github.com/szsdk/biblatex-gbt77142005)的（实际上是caspervector的），有部分重合。

**Comment by zepinglee** [comment]
貌似有很多是一样的，可以利用一下。

PS 我感觉很多人喜欢用 natbib ，但是跟 biblatex 不兼容，

**Comment by szsdk** [comment]
实际上，我没有太多使用BibTeX的经验。只是因为biblatex比较新一点，所有认为biblatex应该会有更好的设计。而且似乎biblatex对中文支持会更好一些？

**Comment by zepinglee** [comment]
嗯，bibtex 只能按字节处理，biblatex 支持 unicode，

但是主流的杂志貌似还是用的 natbib。所以还是用了 bibtex ，避免用户修改太多内容吧

**Comment by ctexlive** [comment]
看了下附录部分参考文献，也不多，干脆手动录入好了，分配几个人认领完成．
英文文献（包括在google学术，知网检索页面检索）都可以通过zotero等文献管理器自动一键下载．
中文类的必须手工输入，因为没有良好的数据库．
